/**
 * Cordis-free React primitives styled only through `--dsw-*` tokens.
 */

export { StateDot } from './StateDot.tsx'
export type { StateDotState } from './StateDot.tsx'
export { DisclosureRow } from './DisclosureRow.tsx'
export type { DisclosureRowProps } from './DisclosureRow.tsx'
export { Button } from './Button.tsx'
export type { ButtonVariant } from './Button.tsx'
export { Pill } from './Pill.tsx'
export { Input } from './Input.tsx'
export { Menu } from './Menu.tsx'
export type { MenuEntry, MenuItem, MenuSeparator, MenuLabel } from './Menu.tsx'
export { useAnchoredMaxHeight } from './useAnchoredMaxHeight.ts'
export { HoverCard } from './HoverCard.tsx'
export { Modal } from './Modal.tsx'
export { OnboardingSurface } from './OnboardingSurface.tsx'
export { RiskConfirmation } from './RiskConfirmation.tsx'
export type { RiskConfirmationProps } from './RiskConfirmation.tsx'
export { ConnectionBanner } from './ConnectionBanner.tsx'
export { FishLogo } from './FishLogo.tsx'
export { BrandWordmark } from './BrandWordmark.tsx'
export { Tooltip } from './Tooltip.tsx'
export type { TooltipSide } from './Tooltip.tsx'
export { Toast } from './Toast.tsx'
export { writeClipboard } from './clipboard.ts'
export { JsonTree } from './JsonTree.tsx'
export type { JsonTreeProps, JsonTreeLabels } from './JsonTree.tsx'
export { TerminalBlock, DEFAULT_TERMINAL_MAX_LINES } from './TerminalBlock.tsx'
export type { TerminalBlockProps, TerminalBlockLabels } from './TerminalBlock.tsx'
export { ReadBlock, DEFAULT_READ_MAX_LINES } from './ReadBlock.tsx'
export type { ReadBlockProps, ReadBlockLine } from './ReadBlock.tsx'
export { DiffBlock, DEFAULT_DIFF_MAX_LINES } from './DiffBlock.tsx'
export type { DiffBlockProps, DiffHunk } from './DiffBlock.tsx'
export { SearchBlock, DEFAULT_SEARCH_MAX_LINES } from './SearchBlock.tsx'
export type {
  SearchBlockProps, SearchMatchesBlockProps, SearchPathsBlockProps, SearchFileGroup, SearchBlockLineMatch,
} from './SearchBlock.tsx'
export { WebBlock } from './WebBlock.tsx'
export type { WebBlockProps, WebSearchBlockProps, WebFetchBlockProps, WebSourceView } from './WebBlock.tsx'
export { CodeBlock } from './markdown/CodeBlock.tsx'
export type { CodeBlockProps } from './markdown/CodeBlock.tsx'
export { JsonBlock } from './markdown/JsonBlock.tsx'
export { MarkdownText } from './markdown/MarkdownText.tsx'
export type { MarkdownCodeLabels, MarkdownFileMentions } from './markdown/MarkdownText.tsx'
export { MessageText } from './markdown/MessageText.tsx'
export { extractMarkdownPlainText } from './markdown/plain-text.ts'
export type { MarkdownPlainTextMode, MarkdownPlainTextOptions } from './markdown/plain-text.ts'
export * from './icons/index.tsx'
export { cn } from './components/ui/cn.ts'
export { ShadcnButton } from './components/ui/button.tsx'
export type { ShadcnButtonProps, ShadcnButtonVariant, ShadcnButtonSize } from './components/ui/button.tsx'
export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuPortal,
  DropdownMenuContent,
  DropdownMenuItem,
} from './components/ui/dropdown-menu.tsx'
export { Badge } from './components/ui/badge.tsx'
export type { BadgeProps, BadgeVariant } from './components/ui/badge.tsx'
export { Skeleton } from './components/ui/skeleton.tsx'
export { Separator } from './components/ui/separator.tsx'
export { Label } from './components/ui/label.tsx'
export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent } from './components/ui/card.tsx'
export { Alert, AlertTitle, AlertDescription } from './components/ui/alert.tsx'
export type { AlertVariant } from './components/ui/alert.tsx'
export { Textarea } from './components/ui/textarea.tsx'
export { Kbd } from './components/ui/kbd.tsx'
export { Checkbox } from './components/ui/checkbox.tsx'
export { Switch } from './components/ui/switch.tsx'
export { RadioGroup, RadioGroupItem } from './components/ui/radio-group.tsx'
export { Slider } from './components/ui/slider.tsx'
export { Progress } from './components/ui/progress.tsx'
export { Toggle } from './components/ui/toggle.tsx'
export type { ToggleVariant, ToggleSize } from './components/ui/toggle.tsx'
export { ToggleGroup, ToggleGroupItem } from './components/ui/toggle-group.tsx'
export { Avatar, AvatarImage, AvatarFallback } from './components/ui/avatar.tsx'
export { AspectRatio } from './components/ui/aspect-ratio.tsx'

// Shadcn component library (ui-primitives token style). Barrel re-exports:
// each file's named exports are additive and non-colliding, except `Input`
// (aliased below to avoid shadowing the legacy token-styled `Input`).
export * from './components/ui/accordion.tsx'
export * from './components/ui/alert-dialog.tsx'
export * from './components/ui/breadcrumb.tsx'
export * from './components/ui/button-group.tsx'
export * from './components/ui/calendar.tsx'
export { enUS, zhCN } from 'react-day-picker/locale'
export * from './components/ui/carousel.tsx'
export * from './components/ui/chart.tsx'
export * from './components/ui/collapsible.tsx'
export * from './components/ui/combobox.tsx'
export * from './components/ui/command.tsx'
export * from './components/ui/context-menu.tsx'
export * from './components/ui/dialog.tsx'
export * from './components/ui/drawer.tsx'
export * from './components/ui/empty.tsx'
export * from './components/ui/form.tsx'
export * from './components/ui/input-group.tsx'
export * from './components/ui/input-otp.tsx'
export * from './components/ui/menubar.tsx'
export * from './components/ui/native-select.tsx'
export * from './components/ui/navigation-menu.tsx'
export * from './components/ui/pagination.tsx'
export * from './components/ui/popover.tsx'
export * from './components/ui/resizable.tsx'
export * from './components/ui/scroll-area.tsx'
export * from './components/ui/select.tsx'
export * from './components/ui/sheet.tsx'
export * from './components/ui/sidebar.tsx'
export * from './components/ui/sonner.tsx'
export * from './components/ui/spinner.tsx'
export * from './components/ui/table.tsx'
export * from './components/ui/tabs.tsx'
export { Input as ShadcnInput } from './components/ui/input.tsx'

// Shadcn chat primitives (newer registry; Field/Item/Message are collision-free).
export * from './components/ui/field.tsx'
export * from './components/ui/item.tsx'
export * from './components/ui/direction.tsx'
export * from './components/ui/attachment.tsx'
export * from './components/ui/bubble.tsx'
export * from './components/ui/marker.tsx'
export * from './components/ui/message.tsx'
export * from './components/ui/message-scroller.tsx'
